FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 5000

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["FinanceFlow.API/FinanceFlow.API.csproj", "FinanceFlow.API/"]
COPY ["FinanceFlow.Application/FinanceFlow.Application.csproj", "FinanceFlow.Application/"]
COPY ["FinanceFlow.Domain/FinanceFlow.Domain.csproj", "FinanceFlow.Domain/"]
COPY ["FinanceFlow.Infrastructure/FinanceFlow.Infrastructure.csproj", "FinanceFlow.Infrastructure/"]

RUN dotnet restore "FinanceFlow.API/FinanceFlow.API.csproj"

COPY . .

RUN dotnet publish "FinanceFlow.API/FinanceFlow.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .

ENV ASPNETCORE_URLS=http://+:5000
ENV ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "FinanceFlow.API.dll"]